In [32]:
import torch
import numpy as np

## 基本数据类型

In [92]:
a = torch.FloatTensor(2,3)
a

tensor([[8.4078e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [8]:
a = torch.IntTensor(2,3)
a

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [10]:
a = torch.LongTensor(2,3)
a

tensor([[0, 0, 0],
        [0, 0, 0]])

In [14]:
a = torch.randn(2,3)
a

tensor([[-1.4201, -1.6554, -0.5253],
        [-0.8729, -1.0664, -1.1412]])

In [15]:
a.type()

'torch.FloatTensor'

In [16]:
type(a)#pythontype不能具体

torch.Tensor

In [17]:
isinstance(a,torch.FloatTensor)#做合法化检验

True

In [18]:
torch.tensor(1.)#dim为0的标量

tensor(1.)

In [24]:
x= torch.tensor(1.4)
x

tensor(1.4000)

In [23]:
x.shape#0维

torch.Size([])

In [27]:
x.size()

torch.Size([])

In [28]:
torch.tensor([1.2])#1维的张量

tensor([1.2000])

In [29]:
torch.FloatTensor(1)

tensor([-7.0065e-45])

In [30]:
torch.FloatTensor(2)

tensor([0.0000e+00, 5.8413e-06])

In [31]:
torch.FloatTensor(2,4)

tensor([[ 0.0000e+00, -2.5244e-29,  0.0000e+00, -2.5244e-29],
        [ 8.4078e-45,  0.0000e+00,  6.0089e-24,  1.4013e-45]])

In [36]:
data = np.ones((4,5))
data

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
tdata = torch.from_numpy(data)#numpy数组转化为tensor
tdata

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

In [40]:
tdata.numpy()

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
a = torch.ones(2)
a

tensor([1., 1.])

### a.shape 方法和a.size()函数返回相同

In [51]:
a = torch.randn(2,3)
a

tensor([[ 0.8784, -1.2266,  0.1636],
        [-1.8244, -0.7501, -0.5762]])

In [53]:
a.shape[0]

2

In [54]:
a.size(0)

2

In [56]:
a = torch.rand(2,3,4)
a

tensor([[[0.9578, 0.3002, 0.4800, 0.0303],
         [0.3051, 0.8316, 0.7797, 0.8049],
         [0.9761, 0.5088, 0.1089, 0.3348]],

        [[0.5503, 0.7048, 0.5687, 0.8617],
         [0.8609, 0.9901, 0.1800, 0.9454],
         [0.6118, 0.8566, 0.9297, 0.2147]]])

### 切片

In [57]:
a[0]

tensor([[0.9578, 0.3002, 0.4800, 0.0303],
        [0.3051, 0.8316, 0.7797, 0.8049],
        [0.9761, 0.5088, 0.1089, 0.3348]])

In [59]:
a[0,2]

tensor([0.9761, 0.5088, 0.1089, 0.3348])

In [60]:
a[1,2,3,]

tensor(0.2147)

In [136]:
a = torch.rand(2,3,28,28)

In [142]:
a.index_select(1, torch.tensor([0,2])).shape
# index_select(dim, index) 

torch.Size([2, 2, 28, 28])

In [143]:
a[...].shape#...代表任意多的维度

torch.Size([2, 3, 28, 28])

In [145]:
a[0,...].shape

torch.Size([3, 28, 28])

In [146]:
a[:,1,...].shape


torch.Size([2, 28, 28])

In [148]:
a[0,...,::2].shape

torch.Size([3, 28, 14])

In [149]:
x = torch.randn(3,4)
x

tensor([[ 0.0352, -0.5565, -0.4821,  0.6859],
        [-0.9470,  0.8812,  0.7185,  0.1086],
        [ 1.3936, -1.6194, -0.4430, -0.6423]])

In [151]:
mask = x.ge(0.5)#ge大于等于
mask

tensor([[False, False, False,  True],
        [False,  True,  True, False],
        [ True, False, False, False]])

In [153]:
torch.masked_select(x,mask)#取出mask为True的值

tensor([0.6859, 0.8812, 0.7185, 1.3936])

In [63]:
a = torch.rand(2,3,28,28)#彩色图片【b,c,h,w】


In [64]:
a.shape

torch.Size([2, 3, 28, 28])

In [65]:
a.numel()#具体大小，2*3*28*28，等同numpy 的。size

4704

In [68]:
a.dim()

4

In [81]:
n = np.random.randn(2,3,28,28)

In [85]:
n.size

TypeError: 'int' object is not callable

In [88]:
n.dtype

dtype('float64')

In [97]:
x = torch.empty(1)#未初始化的数据，随机数据非常不规则
x

tensor([9.3677e-30])

In [98]:
#更换默认数据类型
print(torch.tensor([1.2, 3]).type())
torch.set_default_tensor_type(torch.DoubleTensor)
print(torch.tensor([1.2, 3]).type())

torch.FloatTensor
torch.DoubleTensor


In [99]:
torch.set_default_tensor_type(torch.FloatTensor)

### 随机初始化

In [101]:
a = torch.rand(3,4)
a

tensor([[0.9688, 0.7287, 0.4875, 0.0907],
        [0.4210, 0.2538, 0.4558, 0.6784],
        [0.8072, 0.9879, 0.9671, 0.8929]])

In [102]:
b = torch.rand_like(a)#把a的shape传给b
b

tensor([[0.3177, 0.2811, 0.3391, 0.5767],
        [0.5883, 0.4222, 0.4403, 0.6356],
        [0.9337, 0.0807, 0.0586, 0.4433]])

In [106]:
c = torch.randint(10,[3,4])#randint(low=0, high, size,）size就是shape是个列表
c

tensor([[7, 5, 4, 3],
        [6, 2, 9, 1],
        [5, 5, 7, 8]])

In [108]:
torch.randn(3,4)#正态分布

tensor([[-0.4353,  0.9222, -1.0256, -0.1064],
        [ 1.6302,  0.3857,  1.6257, -0.2568],
        [-0.9674,  0.9762,  0.3419,  1.8999]])

#### torch.normal(4,3)
#### normal(mean, std,)

In [112]:
torch.full([3,4],7)

tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])

In [113]:
np.full([3,4],7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [114]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [115]:
torch.linspace(1,10,9)

tensor([ 1.0000,  2.1250,  3.2500,  4.3750,  5.5000,  6.6250,  7.7500,  8.8750,
        10.0000])

In [132]:
torch.logspace(-2,2,5)#logspace(a,b,n)，创建行向量，第一个是10^a，最后一个10^b，形成总数为n个元素的等比数列
# logspace(start, end, steps=100, base=10.0)


'torch.FloatTensor'

In [129]:
torch.logspace(-2,2,5,9)

tensor([1.2346e-02, 1.1111e-01, 1.0000e+00, 9.0000e+00, 8.1000e+01])

In [131]:
np.logspace(-2,2,5,base =9)
# np.logspace(
#     start,
#     stop,
#     num=50,
#     endpoint=True,
#     base=10.0,
#     dtype=None,
#     axis=0,
# )

array([1.23456790e-02, 1.11111111e-01, 1.00000000e+00, 9.00000000e+00,
       8.10000000e+01])

## ones,zeros,eye和numpy相同

## numpy的shuffle没有，用randperm来做相同操作


In [154]:
# view和reshape功能相同
a = torch.rand(4,1,28,28)

In [155]:
a.reshape(4,28,28).shape

torch.Size([4, 28, 28])

In [157]:
a.view(4,28*28).shape

torch.Size([4, 784])

In [160]:
a.reshape([4,28,28]).shape

torch.Size([4, 28, 28])

In [161]:
b = a.view(4,28*28)
b.shape

torch.Size([4, 784])

In [165]:
a = b.reshape(4,28,28,1)#逻辑bug
a.shape

torch.Size([4, 28, 28, 1])

In [167]:
a = b.reshape(4,1,28,28)
a.shape

torch.Size([4, 1, 28, 28])

In [168]:
# squeeze挤压,unsqueeze松开
a.unsqueeze(0).shape#参数是位置，增加维度


torch.Size([1, 4, 1, 28, 28])

In [174]:
b = a.unsqueeze(-1)
b.shape

torch.Size([4, 1, 28, 28, 1])

In [176]:
b.squeeze().shape#squeeze, 不加参数回删除所有长度为1的维度

torch.Size([4, 28, 28])

In [177]:
b.squeeze(4).shape#参数是位置，删除维度

torch.Size([4, 1, 28, 28])

In [178]:
# b.unsqueeze()必须有参数

TypeError: unsqueeze() missing 1 required positional arguments: "dim"

In [ ]:
# expand扩展，参数是新的维度

In [179]:
a = torch.rand(4,32,14,14)
b = torch.rand(1,32,1,1)

In [201]:
b.expand(4,32,14,14).shape#增加维度信息,如果原来不是1，无法扩张，会报错。copy默认为false

torch.Size([4, 32, 14, 14])

In [183]:
b.shape

torch.Size([1, 32, 1, 1])

In [186]:
c = b.expand(4,32,15,15)

In [192]:
b.expand(-1,-1,32,4).shape#-1代表数据不变

torch.Size([1, 32, 32, 4])

In [193]:
#repeat是重复维度，传入参数是维度上重复的次数

In [194]:
b.size()

torch.Size([1, 32, 1, 1])

In [196]:
b.repeat(4,32,1,1).shape#在维度上和所给参数做了乘法

torch.Size([4, 1024, 1, 1])

In [200]:
b.repeat(4,1,32,32).shape

torch.Size([4, 32, 32, 32])

In [205]:
a = torch.rand(3,5)

In [206]:
a.t().shape#t代表转秩，指适合2D数据（矩阵）

torch.Size([5, 3])

In [207]:
b.shape

torch.Size([1, 32, 1, 1])

In [209]:
a= torch.rand(4,3,32,32)
a.shape

torch.Size([4, 3, 32, 32])

In [213]:
# transpose交换维度，参数是要交换的两个维度
a1 = a.transpose(1,3)
a1.shape

torch.Size([4, 32, 32, 3])

In [221]:
a1 = a1.reshape(4,3*32*32).reshape(4,3,32,32)## 注意，这样虽然维度相同了，但原来数据被打乱了
a1.shape

torch.Size([4, 3, 32, 32])

In [223]:
a2 = a.transpose(1,3).reshape(4,3*32*32).reshape(4,3,32,32)

In [226]:
aa = a.transpose(1,3).contiguous()#contiguous把数据重新变连续


torch.Size([4, 32, 32, 3])

In [233]:
# a[B,C,H,W]要把维度信息跟踪住就可以恢复
a3 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,32,32,3).transpose(3,1)
#             [BWHC]       [BWHC]                                     [BWHC]      [BCHW]
a3.shape

torch.Size([4, 3, 32, 32])

In [231]:
torch.all(torch.eq(a,a1))

tensor(False)

In [232]:
torch.all(torch.eq(a,a3))#看到a3和a相同

tensor(True)

# 合并和拆分


In [240]:
a = torch.rand(4,32,8)
b = torch.rand(15,32,8)


In [241]:
torch.cat([a,b],dim = 0).shape#要求不是合并的维度上要匹配

torch.Size([19, 32, 8])

In [243]:
a = torch.rand(32,8)
b = torch.rand(32,8)


In [249]:
c = torch.stack([a,b],dim=0)#将两个表合并，增加一个更高的维度
c.shape

torch.Size([2, 32, 8])

In [250]:
# spilt根据长度来拆分。
aa,bb = c.split([1,1],dim=0)

In [251]:
aa.shape,bb.shape

(torch.Size([1, 32, 8]), torch.Size([1, 32, 8]))

In [252]:
aa,bb=c.split([15,17],dim =1)

In [253]:
aa.shape,bb.shape

(torch.Size([2, 15, 8]), torch.Size([2, 17, 8]))

In [254]:
#chunk按照数量拆分

In [255]:
c.shape

torch.Size([2, 32, 8])

In [257]:
aa ,bb = c.chunk(2, dim=0)

In [258]:
aa.shape,bb.shape

(torch.Size([1, 32, 8]), torch.Size([1, 32, 8]))

In [259]:
# + - * /   **    sqrt()开方 。rsqrt=  **（0.5）是平方根的倒数

In [260]:
# matmul矩阵相乘，2D数据可用简写‘mm’不推荐，可以用符号@和matmul相同

In [262]:
a = torch.rand(4,784)
w = torch.rand(32,784)
(a@w.t()).shape#.t只适合2D矩阵
a相当于一个照片，通过矩阵相乘达到降维的效果

torch.Size([4, 32])

In [266]:
# 高维乘法，只取最后两维做运算,
a = torch.rand(4,3,28,64)
b = torch.rand(4,3,64,32)
# (a@b).shape
torch.matmul(a,b).shape

torch.Size([4, 3, 28, 32])